## Raison d'être
This notebook is to explain why `(A+A')*x` can be used to verify `ForwardDiff.gradient(x->x'A*x,x)` in `./Automatic Differentiation in 10 Minutes.ipynb`.

### `size` of an array in Julia
Since I am still relatively new to Julia, let's recall how Julia deals with **shapes/sizes**.

In [1]:
A = randn(3,3)

3×3 Array{Float64,2}:
 -0.131067   2.09169   -1.55142
 -1.16364   -0.578139   2.25998
 -0.461744  -1.61132    1.299

In [2]:
size(A)

(3, 3)

In [3]:
x = randn(3)

3-element Array{Float64,1}:
  0.8572035090290636
  1.100279349189294
 -0.5877937613435069

In [4]:
size(x)

(3,)

In [5]:
A*x

3-element Array{Float64,1}:
  3.1010046540491953
 -2.961991502064001
 -2.9322573933725877

In [6]:
size(A*x)

(3,)

In [7]:
size(x')

(1, 3)

In [8]:
size(x'*A')

(1, 3)

In [9]:
A*reshape(x,3,1)

3×1 Array{Float64,2}:
  3.101004654049196
 -2.961991502064001
 -2.9322573933725877

In [10]:
size(A*reshape(x,3,1))

(3, 1)

In [11]:
x'*x

2.290914008018504

In [15]:
x'*reshape(x,3,1)

1×1 LinearAlgebra.Adjoint{Float64,Array{Float64,1}}:
 2.290914008018504

### Differential
$$
\begin{align*}
  f:\quad &\mathbb{R}^n \to \mathbb{R} \\
       &x \mapsto x^{T}Ax
\end{align*}
$$


For all $x, h \in \mathbb{R}^{n}$, We have
$$
\begin{align*}
  f(x+h) &= (x+h)^{T} A (x+h)                      \\
         &= x^{T}Ax + h^{T}Ax + x^{T}Ah + h^{T}Ah  \\
         &= f(x) + x^{T}A^{T}h + x^{T}Ah + h^{T}Ah  \\
         &= f(x) + x^{T}(A^{T} + A)\,h + h^{T}Ah\,.  \\
\end{align*}
$$

Since the transformation $h \mapsto x^{T}(A^{T} + A)\,h$ is linear, if we can prove that $h^{T}Ah = o(\lVert h \rVert)$, then we have $\nabla f(x) =
\left(x^{T}(A^{T} + A)\right)^{T} = (A + A^{T})x.$